version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=recipe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
